#!/usr/bin/env bash

# For a list of available casks:
#
# - visit https://formulae.brew.sh/cask/
# - or run `brew -S [query]`

brew install autojump 
brew install nvm

brew install --cask adobe-creative-cloud
brew install --cask alfred
brew install --cask docker
brew install --cask slack
brew install --cask iterm2
brew install --cask gitkraken
brew install --cask google-chrome
brew install --cask rectangle
brew install --cask setapp
brew install --cask spotify
brew install --cask visual-studio-code
brew install insomnia

PRIVATE_DEVICE=1

while getopts p opt; do
    case $opt in
    p)
        PRIVATE_DEVICE=0
        ;;
    esac
done

if [ $PRIVATE_DEVICE = 0 ]; then
    brew install --cask ableton-live-suite
    brew install --cask dropbox
    brew install --cask guitar-pro
    brew install --cask lastfm
    brew install --cask thinkorswim
fi
